[package]
name = "arch-installer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = { version = "0.10.2", features = ["fuzzy-select"] }
prettytable-rs = "0.9.0"
